[package]
name = "villu0769/slite-client"
version = "0.1.0"
description = "Slite Client"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
"/public" = "dist" 

[[command]]
name = "script"
module = "wasmer/static-web-server:webserver"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
env = [
  "SERVER_PORT=8080", 
  "ROOT=/public", 
  "SERVER_PAGE_FALLBACK=/public/index.html"
]